### ISSUE TITLE
final classes unavailable for Mocks

### ISSUE THREAD

**Issue by EvsenevDev** [ferranabello/Viperit#38]
Hi, i really like your framework and template for Xcode.
But classes from template are **final** and unavailable for inherence and **Mocking** in Unit Tasts.
Can you add new Template or change it to not final classes for layers **Router**, **Interactor**, **Presenter**? Or if you want i can create pull request to you.

P.S. Maybe add optional check box to module creation window (like "Layers are **final**")?

**Comment by ferranabello** [comment]
Hi @EvsenevDev,
you are right. Using the current templates and injectMock methods, there is a need to have inheritance in order to test router, interactor and presenter .

What I'm thinking here is to have 2 different templates.

- The first one, will be like you are saying. So, classes won't be final, and subclassing will be required in order for mocking to be done.

- The second one, will be what I think we could call "Protocol-oriented module", which will have protocols for each component of the module. This solution will let us test the code in a protocol-oriented way. So the components will be final, and no inheritance will be necessary.

The first template will be the faster, or the easier solution for simple projects. And the second one will probably be better for using in larger or more complex projects.

Swift gave us protocols, so let's use them :-)

If you can do a PR removing the final keyword for the template I'll very much appreciate it. It should be very straight-forward, just removing the final keyword where necessary.

Remember that the repo for the templates is this one:
https://github.com/ferranabello/ViperitTemplates

Thanks a lot for your contribution! :-)

**Comment by ferranabello** [comment]
The inheritance template has been successfully created and merged in #39
