### ISSUE TITLE
How to integrate the 'Eureka' framework

### ISSUE THREAD

**Issue by QianJiaming** [ferranabello/Viperit#69]
First of all, thank you very much for the Viper framework you provide. It's really very simple to use.
Now I have a problem. I want to integrate the 'Eureka' framework. This framework can easy to build form.
But needs to inherit the 'FormViewController'.

In Viper framework, the 'UserInterface' class is inherit 'UIViewController'.
So, could you help me?

**Comment by ferranabello** [comment]
Hi @QianJiaming I'm glad to hear that.

About Eureka, I never used it, but it looks like an all-in-one solution. If you need to use eureka for your form views only, I would suggest you to integrate it inside your module's view. Just as you would do when you need to use a UITableView, UIView or any other custom view. 

Using Viper I would think as Eureka as any other custom view (besides it actually is a bit more complex because it inherits from UIViewController).

Let's say you have a module Login, you could have these classes:

- LoginRouter
- LoginPresenter
- **LoginView** (here you can have a subview acting as a container for your **LoginFormView: FormViewController**)
- LoginInteractor

Let me know what you think.

**Comment by QianJiaming** [comment]
Thank you very much! I got it.
